[project]
name = "icebergfyi-website"
version = "0.1.0"
description = "Browser for test results of Iceberg.FYI"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi[standard]>=0.115.8",
    "jinja2>=3.1.5",
]
